### ISSUE TITLE
Greaseweazle PCB - BOM

### ISSUE THREAD

**Issue by ch0mik** [keirf/PCB-Projects#2]
Hi,

Please add to Greaseweazle PCB BOM list

with Regards
Pawel

PS. please describe diffrents gw-26 vs greaseweazle

**Comment by keirf** [comment]
I have also added a note on USBPU, as this must not be populated unless the Pill is modified. You would normally only do this is the BP pull-up resistor is incorrect value, which these days I think would be very rare.
