### ISSUE TITLE
Cannot burn 27c400 - only read

### ISSUE THREAD

**Issue by kissedin** [keirf/PCB-Projects#4]
Hi! It was several years since i bought my adapter (ver 3). I have used it to read 27c400 Roms several times.

But this week i needed to burn 5 eproms. I could not burn a single bit to any of them. 

I get this message (kind of): "error! Adress 0x00000  buffer xxxxxx verify FFFFFf". 

When i check voltage on vpp it is -12V (Yes minus 12 v).

I've checked all resistors and even tried to with a new transistor. No change. I've erased with uv. I can burn roms that don't require adapter. What could be the issue here? Plugged in usb backwards? :)

**Comment by keirf** [comment]
Well.... It could be a bad adapter I guess? I would expect -12v Vpp to kill your EPROM by the way. Adapter doesn't generate -12v itself so it's unclear where that would be coming from and why.

**Comment by kissedin** [comment]
Well... I tried another adapter today and could burn successfuly. Eprom seem ok too.

**Comment by keirf** [comment]
I think we can conclude the adapter is busted then.

**Comment by keirf** [comment]
Unusual failure mode. But it could well be something to do with the ZIF socket. Those are not premium quality.

**Comment by kissedin** [comment]
Yes. Or maybe one of them  copper traces. Anyway I'm glad i can burn my roms.
